### ISSUE TITLE
Does not work in Fedora 39 Beta/Gnome 45

### ISSUE THREAD

**Issue by jcodesreal** [francislavoie/gnome-shell-volume-scroller#1]
It comes up with this error when you try to open the settings menu also:

The settings of extension volume_scroller@francislavoie.github.io had an error:
```
SyntaxError: import declarations may only appear at top level of a module
```

Stack trace:
```
@file:///home/joe/.local/share/gnome-shell/extensions/volume_scroller@francislavoie.github.io/prefs.js:3:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by sgrzy01** [comment]
Just wanted to "second" this... of all the extensions that I lost with G45, I miss this one the most... I know it's no simple effort based on what I am seeing in discussions with other extensions, but wanted to let you know it's missed...

More than happy to test since I can't really help with code....

Thanks!.

**Comment by francislavoie** [comment]
Sorry about this... apparently I don't automatically get notifications from Github on my own repo if it's a fork?? 🤦‍♂️ Turned on notifications now. Reviewing #2.

**Comment by francislavoie** [comment]
I've tagged https://github.com/francislavoie/gnome-shell-volume-scroller/releases/tag/v12. Please try it out! I don't use Gnome 45 so I can't test it myself. Instructions at https://github.com/francislavoie/gnome-shell-volume-scroller#manual-installation

I've also submitted the update to https://extensions.gnome.org/extension/5904/volume-scroller/ and it's pending review.
