### ISSUE TITLE
wish to support gnome 46

### ISSUE THREAD

**Issue by plainee** [francislavoie/gnome-shell-volume-scroller#6]
wish to support gnome 46

**Comment by francislavoie** [comment]
Added support https://github.com/francislavoie/gnome-shell-volume-scroller/compare/v13...v14

Uploading a new build now (under review). I don't use Gnome 45/46 so I can't test that it works as expected, hopefully no API changes were required.

**Comment by francislavoie** [comment]
It's approved and up. Let me know if there's any problem.
