### ISSUE TITLE
Volume controls are inverted on touchpads with natural scrolling enabled!

### ISSUE THREAD

**Issue by salihefee** [francislavoie/gnome-shell-volume-scroller#7]
When natural scrolling is enabled in GNOME touchpad settings, scrolling up decreases the volume, and scrolling down increases the volume.

**Comment by francislavoie** [comment]
PRs welcome to fix this if you like. I don't plan on adding any new features myself, this is feature complete for my needs.

Either the trackpad scroll direction could be queried and considered (if that's an available API, no idea if it is) or simply another config option could be added to toggle the scroll direction.

**Comment by francislavoie** [comment]
Fixed in https://github.com/francislavoie/gnome-shell-volume-scroller/pull/9

I'll get this uploaded in the next couple hours.

**Comment by salihefee** [comment]
Thanks.
